# Generated by Django 4.0 on 2021-12-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='repassword',
            new_name='password_2',
        ),
    ]
