# Generated by Django 4.0 on 2021-12-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_repassword_user_password_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
